name: GemsEconomy
main: me.xanium.gemseconomy.GemsEconomy
version: ${project.version}
author: Xanium
description: A multi-currency economy plugin for spigot servers!
website: https://www.spigotmc.org/resources/gemseconomy.19655/
load: STARTUP
loadbefore:
  - ItemFrameShops
depend:
  - MegumiLib
  - DataManager
  - PlaceholderAPI
softdepend:
  - Vault
commands:
  balance:
    description: Shows your balances
    aliases: [gbal, gmoney, bal, money]
  baltop:
    description: Shows the top balances of the server
    aliases: [gmoneytop, gecotop, gtop, gbaltop]
  currency:
    description: Manage the currencies.
    aliases: [gcurr, gemscurrencies, gcurrency, currencies]
  economy:
    description: Give, set or take currency.
    aliases: [geconomy, eco, geco, gemseconomy]
  pay:
    description: Pays another account
    aliases: [gpay, gemspay]
  exchange:
    usage: /exchange
    description: Exchange currencies.
    aliases: [gex, gemsexchange, gexchange]