name: GemsEconomy
main: net.sakuragame.eternal.gemseconomy.GemsEconomy
version: ${project.version}
author: [Xanium, justwei]
description: A multi-currency economy plugin for spigot servers!
depend:
  - Vault
  - MegumiLib
  - DataManager
  - PlaceholderAPI
commands:
  balance:
    description: Shows your balances
    aliases: [gbal, gmoney, bal, money]
  currency:
    description: Manage the currencies.
    aliases: [gcurr, gemscurrencies, gcurrency, currencies]
  economy:
    description: Give, set or take currency.
    aliases: [geconomy, eco, geco, gemseconomy]
  pay:
    description: Pays another account
    aliases: [gpay, gemspay]
  exchange:
    usage: /exchange
    description: Exchange currencies.
    aliases: [gex, gemsexchange, gexchange]